# Generated by Django 4.0.1 on 2022-07-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='prod', max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(default='', max_length=1023)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
