# Generated by Django 4.0.1 on 2022-07-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/newFiles'),
        ),
    ]
