# Generated by Django 4.0.1 on 2022-07-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0002_alter_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='else', max_length=127),
        ),
    ]
