# Generated by Django 4.0.1 on 2022-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion', '0006_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='col',
            field=models.IntegerField(default=0),
        ),
    ]
